// Package converter provides XLSX/CSV to JSON conversion for transcription files.
//
// It supports two input modes:
//
//  1. Template mode — XLSX files generated by the backend, which contain a
//     hidden "_metadata" sheet with audio_file, language, and output_name,
//     plus a "Sheet1" with fixed columns (segment_id, start_time, …).
//
//  2. Vendor mode — XLSX/CSV files from external vendors with inconsistent
//     column names. Columns are auto-detected via the colmap package, and
//     language/audio metadata is inferred from the file path/name.
//
// Both modes produce the same JSON output format:
//
//	{
//	  "audio_name": "...",
//	  "utterances": [
//	    {
//	      "speaker": "speaker_01",
//	      "start_time": 1.23,
//	      "end_time": 4.56,
//	      "transcript": "...",
//	      "non_speech_events": { "emotions": "neutral" },
//	      "language_attributes": { "language": "English", "locale": "en-US", "accent": "Standard English" }
//	    }
//	  ]
//	}
package converter

import (
	"encoding/csv"
	"encoding/json"
	"fmt"
	"log/slog"
	"math"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"time"

	"github.com/xuri/excelize/v2"

	"transcription-cli/internal/colmap"
	"transcription-cli/internal/langutil"
	"transcription-cli/internal/logging"
)

// ---------------------------------------------------------------------------
// Output types — matches the Python scripts' JSON format
// ---------------------------------------------------------------------------

// Transcription is the top-level JSON output.
type Transcription struct {
	AudioName  string      `json:"audio_name"`
	Utterances []Utterance `json:"utterances"`
}

// Utterance is a single transcription segment.
type Utterance struct {
	Speaker            string             `json:"speaker"`
	StartTime          *float64           `json:"start_time"`
	EndTime            *float64           `json:"end_time"`
	Transcript         string             `json:"transcript"`
	NonSpeechEvents    NonSpeechEvents    `json:"non_speech_events"`
	LanguageAttributes LanguageAttributes `json:"language_attributes"`
}

// NonSpeechEvents captures non-speech annotations.
type NonSpeechEvents struct {
	Emotions string `json:"emotions"`
}

// LanguageAttributes captures language metadata.
type LanguageAttributes struct {
	Language string `json:"language"`
	Locale   string `json:"locale"`
	Accent   string `json:"accent"`
}

// ---------------------------------------------------------------------------
// Public API — unchanged signatures
// ---------------------------------------------------------------------------

// ConvertAll converts all XLSX/CSV files in xlsxDir to JSON in jsonDir.
func ConvertAll(xlsxDir, jsonDir string) ([]string, error) {
	start := time.Now()

	if err := os.MkdirAll(jsonDir, 0755); err != nil {
		return nil, fmt.Errorf("creating json directory %s: %w", jsonDir, err)
	}

	slog.Info("conversion started", logging.FieldPath, xlsxDir)

	entries, err := os.ReadDir(xlsxDir)
	if err != nil {
		return nil, fmt.Errorf("reading xlsx directory %s: %w", xlsxDir, err)
	}

	var paths []string
	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		lower := strings.ToLower(entry.Name())
		if strings.HasSuffix(lower, ".xlsx") || strings.HasSuffix(lower, ".xls") || strings.HasSuffix(lower, ".csv") {
			paths = append(paths, filepath.Join(xlsxDir, entry.Name()))
		}
	}

	return ConvertFiles(paths, jsonDir, time.Since(start))
}

// ConvertFiles converts only the specified files to JSON in jsonDir.
// Used after QA to convert only approved files.
func ConvertFiles(filePaths []string, jsonDir string, elapsed time.Duration) ([]string, error) {
	start := time.Now().Add(-elapsed)

	if err := os.MkdirAll(jsonDir, 0755); err != nil {
		return nil, fmt.Errorf("creating json directory %s: %w", jsonDir, err)
	}

	var jsonFiles []string
	for _, path := range filePaths {
		trans, outputName, err := Convert(path)
		if err != nil {
			return nil, fmt.Errorf("converting %s: %w", filepath.Base(path), err)
		}

		jsonPath := filepath.Join(jsonDir, outputName+".json")
		data, err := json.MarshalIndent(trans, "", "  ")
		if err != nil {
			return nil, fmt.Errorf("marshaling json for %s: %w", filepath.Base(path), err)
		}

		if err := os.WriteFile(jsonPath, data, 0644); err != nil {
			return nil, fmt.Errorf("writing json file %s: %w", jsonPath, err)
		}

		jsonFiles = append(jsonFiles, jsonPath)
	}

	slog.Info("conversion completed",
		logging.FieldCount, len(jsonFiles),
		logging.FieldDurationMs, time.Since(start).Milliseconds())

	return jsonFiles, nil
}

// Convert transforms a single XLSX or CSV file into a Transcription struct.
// It auto-detects whether the file is a backend template (has _metadata
// sheet) or a vendor file (needs column auto-detection).
func Convert(path string) (*Transcription, string, error) {
	lower := strings.ToLower(path)

	if strings.HasSuffix(lower, ".csv") {
		return convertCSV(path)
	}
	return convertXLSX(path)
}

// ---------------------------------------------------------------------------
// XLSX conversion (template mode or vendor mode)
// ---------------------------------------------------------------------------

func convertXLSX(xlsxPath string) (*Transcription, string, error) {
	f, err := excelize.OpenFile(xlsxPath)
	if err != nil {
		return nil, "", fmt.Errorf("opening xlsx file: %w", err)
	}
	defer func() {
		if closeErr := f.Close(); closeErr != nil {
			slog.Warn("failed to close xlsx file",
				logging.FieldPath, xlsxPath,
				logging.FieldError, closeErr)
		}
	}()

	// Check for _metadata sheet (template mode)
	if hasSheet(f, "_metadata") {
		return convertTemplateXLSX(f, xlsxPath)
	}

	// Vendor mode — auto-detect columns
	return convertVendorXLSX(f, xlsxPath)
}

// hasSheet returns true if the workbook contains a sheet with the given name.
func hasSheet(f *excelize.File, name string) bool {
	for _, s := range f.GetSheetList() {
		if strings.EqualFold(s, name) {
			return true
		}
	}
	return false
}

// ---------------------------------------------------------------------------
// Template mode — reads the backend's own XLSX format
// ---------------------------------------------------------------------------

func convertTemplateXLSX(f *excelize.File, xlsxPath string) (*Transcription, string, error) {
	audioFile, err := f.GetCellValue("_metadata", "B1")
	if err != nil {
		return nil, "", fmt.Errorf("reading audio_file from metadata: %w", err)
	}
	language, err := f.GetCellValue("_metadata", "B2")
	if err != nil {
		return nil, "", fmt.Errorf("reading language from metadata: %w", err)
	}
	outputName, err := f.GetCellValue("_metadata", "B3")
	if err != nil {
		return nil, "", fmt.Errorf("reading output_name from metadata: %w", err)
	}

	if audioFile == "" || language == "" || outputName == "" {
		return nil, "", fmt.Errorf("missing required metadata fields in %s", filepath.Base(xlsxPath))
	}

	rows, err := f.GetRows("Sheet1")
	if err != nil {
		return nil, "", fmt.Errorf("reading data rows: %w", err)
	}

	langDisp := langutil.LanguageDisplay(language)
	accent := "Standard " + langDisp
	locale := langutil.NormalizeLocale("", language)
	audioName := langutil.NormalizeAudioName(audioFile)

	trans := &Transcription{
		AudioName:  audioName,
		Utterances: make([]Utterance, 0, max(len(rows)-1, 0)),
	}

	// Skip header row (index 0)
	for i, row := range rows[1:] {
		if len(row) < 5 {
			continue
		}

		startTime, err := parseFloat(row[1], "start_time", i+2)
		if err != nil {
			return nil, "", err
		}
		endTime, err := parseFloat(row[2], "end_time", i+2)
		if err != nil {
			return nil, "", err
		}

		speaker := langutil.NormalizeSpeaker(row[3])
		transcript := strings.TrimSpace(row[4])
		transcript = langutil.ApplyOverlap(transcript, language)

		utt := Utterance{
			Speaker:         speaker,
			StartTime:       &startTime,
			EndTime:         &endTime,
			Transcript:      transcript,
			NonSpeechEvents: NonSpeechEvents{Emotions: "neutral"},
			LanguageAttributes: LanguageAttributes{
				Language: langDisp,
				Locale:   locale,
				Accent:   accent,
			},
		}

		trans.Utterances = append(trans.Utterances, utt)
	}

	return trans, outputName, nil
}

// ---------------------------------------------------------------------------
// Vendor mode — fuzzy column detection
// ---------------------------------------------------------------------------

func convertVendorXLSX(f *excelize.File, xlsxPath string) (*Transcription, string, error) {
	// Find the first non-empty sheet
	var sheetName string
	for _, s := range f.GetSheetList() {
		if strings.HasPrefix(s, "_") {
			continue
		}
		sheetName = s
		break
	}
	if sheetName == "" {
		return nil, "", fmt.Errorf("no data sheet found in %s", filepath.Base(xlsxPath))
	}

	rows, err := f.GetRows(sheetName)
	if err != nil {
		return nil, "", fmt.Errorf("reading rows from sheet %s: %w", sheetName, err)
	}
	if len(rows) < 2 {
		return nil, "", fmt.Errorf("no data rows found in %s", filepath.Base(xlsxPath))
	}

	// Convert rows to string slices for the common converter
	return convertRows(rows, xlsxPath)
}

// ---------------------------------------------------------------------------
// CSV conversion (always vendor mode)
// ---------------------------------------------------------------------------

func convertCSV(csvPath string) (*Transcription, string, error) {
	file, err := os.Open(csvPath)
	if err != nil {
		return nil, "", fmt.Errorf("opening csv file: %w", err)
	}
	defer file.Close()

	reader := csv.NewReader(file)
	reader.LazyQuotes = true
	reader.TrimLeadingSpace = true

	rows, err := reader.ReadAll()
	if err != nil {
		return nil, "", fmt.Errorf("reading csv file: %w", err)
	}
	if len(rows) < 2 {
		return nil, "", fmt.Errorf("no data rows found in %s", filepath.Base(csvPath))
	}

	return convertRows(rows, csvPath)
}

// ---------------------------------------------------------------------------
// Common vendor-mode conversion (shared between XLSX and CSV)
// ---------------------------------------------------------------------------

func convertRows(rows [][]string, filePath string) (*Transcription, string, error) {
	headers := rows[0]
	cols := colmap.Resolve(headers)

	// Detect language from the file path
	langCode := langutil.DetectLangFromPath(filePath)
	langDisp := langutil.LanguageDisplay(langCode)
	if langDisp == "" {
		langDisp = langCode
	}
	accent := "Standard " + langDisp
	if langDisp == "" {
		accent = "Standard"
	}

	// Derive audio name from the filename or from the audio_name column
	stem := strings.TrimSuffix(filepath.Base(filePath), filepath.Ext(filePath))
	audioName := langutil.NormalizeAudioName(stem)

	if colmap.Has(cols, colmap.ColAudioName) {
		idx := cols[colmap.ColAudioName]
		for _, row := range rows[1:] {
			if idx < len(row) {
				n := langutil.NormalizeAudioName(row[idx])
				if n != "" {
					audioName = n
					break
				}
			}
		}
	}

	// Output name: file stem without audio extensions, underscores → #
	outputName := langutil.NormalizeAudioName(stem)

	trans := &Transcription{
		AudioName:  audioName,
		Utterances: make([]Utterance, 0, len(rows)-1),
	}

	for _, row := range rows[1:] {
		utt := Utterance{
			NonSpeechEvents: NonSpeechEvents{Emotions: "neutral"},
			LanguageAttributes: LanguageAttributes{
				Language: langDisp,
				Locale:   langCode,
				Accent:   accent,
			},
		}

		// Speaker
		if colmap.Has(cols, colmap.ColSpeaker) {
			if idx := cols[colmap.ColSpeaker]; idx < len(row) {
				utt.Speaker = langutil.NormalizeSpeaker(row[idx])
			}
		}

		// Start time
		if colmap.Has(cols, colmap.ColStartTime) {
			if idx := cols[colmap.ColStartTime]; idx < len(row) {
				if v := toFloat(row[idx]); v != nil {
					utt.StartTime = v
				}
			}
		}

		// End time
		if colmap.Has(cols, colmap.ColEndTime) {
			if idx := cols[colmap.ColEndTime]; idx < len(row) {
				if v := toFloat(row[idx]); v != nil {
					utt.EndTime = v
				}
			}
		}

		// Transcript
		if colmap.Has(cols, colmap.ColTranscript) {
			if idx := cols[colmap.ColTranscript]; idx < len(row) {
				utt.Transcript = strings.TrimSpace(row[idx])
				utt.Transcript = langutil.ApplyOverlap(utt.Transcript, langCode)
			}
		}

		// Emotion
		if colmap.Has(cols, colmap.ColEmotion) {
			if idx := cols[colmap.ColEmotion]; idx < len(row) {
				em := strings.ToLower(strings.TrimSpace(row[idx]))
				if em != "" {
					utt.NonSpeechEvents.Emotions = em
				}
			}
		}

		// Locale
		if colmap.Has(cols, colmap.ColLocale) {
			if idx := cols[colmap.ColLocale]; idx < len(row) {
				raw := strings.TrimSpace(row[idx])
				if raw != "" {
					utt.LanguageAttributes.Locale = langutil.NormalizeLocale(raw, langCode)
				}
			}
		} else if langCode != "" {
			utt.LanguageAttributes.Locale = langutil.NormalizeLocale("", langCode)
		}

		trans.Utterances = append(trans.Utterances, utt)
	}

	return trans, outputName, nil
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

func parseFloat(s, fieldName string, rowNum int) (float64, error) {
	s = strings.TrimSpace(s)
	if s == "" {
		return 0, fmt.Errorf("row %d: %s is empty", rowNum, fieldName)
	}
	v, err := strconv.ParseFloat(s, 64)
	if err != nil {
		return 0, fmt.Errorf("row %d: parsing %s value '%s': %w", rowNum, fieldName, s, err)
	}
	return v, nil
}

// toFloat converts a string to *float64, returning nil on failure.
// Handles comma-as-decimal (European format).
func toFloat(s string) *float64 {
	s = strings.TrimSpace(strings.ReplaceAll(s, ",", "."))
	if s == "" {
		return nil
	}
	v, err := strconv.ParseFloat(s, 64)
	if err != nil {
		return nil
	}
	// Round to avoid floating point noise.
	v = math.Round(v*1000) / 1000
	return &v
}
